config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'static_pages#top'
  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :boards do
    member do
      get :confirm_destroy
    end
    resources :comments, only: %i[show create edit update destroy ], shallow: true do
      member do
        get :confirm
      end
    end
  end
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  post 'update_like_count', to: 'likes#update_like_count'
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :board
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy, :confirm]

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.board_id = params[:board_id]  # 明示的に board_id を設定
    if @comment.save
      flash[:info] = "コメントが作成されました"
      redirect_to board_path(@comment.board)
    else
      flash[:danger] = "コメントの作成に失敗しました"
      redirect_to board_path(@comment.board), status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:info] = 'コメントが更新されました'
      redirect_to board_path(@comment.board)
    else
      render :edit
    end
  end

  def confirm
    # 削除確認のための処理
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    @comment.destroy!
    flash[:success] = 'コメントを削除しました'
    redirect_to board_path(@comment.board)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :board_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td>
    <h3 class="small"><%= comment.user.decorate.full_name %></h3>
    <p><%= simple_format(comment.body) %></p>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to edit_comment_path(comment), class: "edit-comment-link btn btn-outline-secondary btn-sm" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to confirm_comment_path(comment), id: "button-delete-#{comment.id}", data: { confirm: '削除しますか？' }, class: 'btn btn-outline-danger btn-sm' do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: board_comments_path(board) do |f| %>
      <%= f.label :body, "コメント", class: "form-label" %>
      <%= f.text_area :body, class: "form-control mb-3", row: "4", placeholder: "コメント", required: true %>
      <%= f.submit "投稿", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/comments/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="card">
        <div class="card-header text-center">
          <h3 class="card-title">コメント削除確認</h3>
          <p>本当にこのコメントを削除しますか？</p>
        </div>
        <div class="card-body">
          <%= form_with url: comment_path(@comment), method: :delete do %>
            <div class="d-flex justify-content-between">
              <%= submit_tag '削除する', class: 'btn btn-danger' %>
              <%= link_to 'キャンセル', board_path(@comment.board), class: 'btn btn-secondary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>コメントを編集</h1>
      <%= form_with model: @comment, local: true do |form| %>
        <div class="form-group">
          <%= form.label :body, "コメント" %>
          <%= form.text_area :body, class: "form-control" %>
        </div>
        <div class="d-flex justify-content-between">
          <%= form.submit "更新", class: "btn btn-primary" %>
          <%= link_to 'キャンセル', board_path(@comment.board), class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>