config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'static_pages#top'
  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :boards do
    member do
      get :confirm_destroy
    end
    resources :comments, only: %i[show create edit update destroy ], shallow: true do
      member do
        get :confirm
      end
    end
  end
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  post 'update_like_count', to: 'likes#update_like_count'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "title", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["comments", "user"]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :board
end

app/models/like.rb
class Like < ApplicationRecord
  validates :question_id, presence: true, uniqueness: true
  validates :like_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/question.rb
class Question < ApplicationRecord
  validates :like_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  #ユーザーが削除のときに、ユーザーにBoardも一緒に削除
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy

  #コメント作成者にだけ、編集と削除ボタンを表示
  def own?(object)
    id == object&.user_id
  end
  validates :reset_password_token, uniqueness: true, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :danger

  private

  def not_authenticated
    flash.now[:danger] = 'ログインしてください'
    redirect_to login_path
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :update, :show, :destroy, :confirm_destroy]
  before_action :check_board_destroy, only: [:confirm_destroy, :destroy]
  before_action :check_board_edit, only: [:edit, :update]

  def index
    @search = Board.ransack(params[:q])
    @boards = @search.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:info] = '掲示板が作成されました'
      redirect_to boards_path
    else
      flash.now[:danger] = '掲示板の作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id]) #bordsテーブルのidを取得している
    @comment = Comment.new #コメントの新規作成
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  def edit
  end

  def update
    if @board.update(board_params)
      flash[:info] = '掲示板が更新されました'
      redirect_to @board
    else
      render :edit
    end
  end

  def confirm_destroy
    # @boardはset_boardで設定済み
  end

  def destroy
    @board.destroy!
    flash[:success] = '掲示板を削除しました'
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:title, :body)
  end

  def set_board
    @board = Board.find(params[:id])
  end

  def check_board_destroy
    unless @board.user_id == current_user.id
      flash[:danger] = '作成した掲示板ではないので、削除できません'
      redirect_to boards_path
    end
  end

  def check_board_edit
    unless @board.user_id == current_user.id
      flash[:danger] = '作成した掲示板ではないので、編集できません'
      redirect_to boards_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy, :confirm]

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.board_id = params[:board_id]  # 明示的に board_id を設定
    if @comment.save
      flash[:info] = "コメントが作成されました"
      redirect_to board_path(@comment.board)
    else
      flash[:danger] = "コメントの作成に失敗しました"
      redirect_to board_path(@comment.board), status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:info] = 'コメントが更新されました'
      redirect_to board_path(@comment.board)
    else
      render :edit
    end
  end

  def confirm
    # 削除確認のための処理
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    @comment.destroy!
    flash[:success] = 'コメントを削除しました'
    redirect_to board_path(@comment.board)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :board_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  protect_from_forgery with: :null_session # APIの場合はCSRF対策を無効化することがある

  def update_like_count
    question_id = params[:question_id]
    like_count = params[:like_count].to_i

    # データベースの質問を検索
    @question = Question.find_by(id: question_id)

    if @question
      # 「いいね」数を更新
      @question.update(like_count: like_count)

      # レスポンスを返す
      render json: { status: 'success', like_count: @question.like_count }
    else
      render json: { status: 'error', message: 'Question not found' }, status: :not_found
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]
  
  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      flash[:info] = 'ログインしました'
      redirect_to boards_path
    else
      flash.now[:danger] = 'ログイン失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:info] = 'ログアウトしました'
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = '新規登録が完了しました'
      redirect_to root_path
    else
      flash.now[:danger] = '新規登録失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <!-- ログインしていたらbeforeに行ってログイン出来ているか確認出来る -->
    <% if logged_in? %> 
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to root_path, class: 'navbar-brand' do %>
      Job Hunting Q&A and Career Advice Board 
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>

        <li class='nav-item'>
          <%= link_to '新規登録', new_user_path, class: 'nav-link' %>
        </li>

        <li class='nav-item'>
          <%= link_to 'ログイン', login_path, class: 'nav-link' %>
        </li>

        <li class='nav-item'>
          <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="navbar navbar-expand-lg navbar-light bg-light">
  <nav class="container">
    <ul class="navbar-nav flex-row">
      <li class="nav-item">
        <a class="nav-link" href="/">お問い合わせ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about">利用規約</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">プライバシーポリシー</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to root_path, class: 'navbar-brand' do %>
      Job Hunting Q&A and Career Advice Board 
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>

        <!-- 掲示板ドロップダウンメニュー -->
        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '掲示板', '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to '掲示板一覧', boards_path, class: 'dropdown-item' %>
            <%= link_to '掲示板作成', new_board_path, class: 'dropdown-item' %>
          </div>
        </li>

        <!-- 新規登録、ログイン、ログアウト -->
        <li class='nav-item'>
          <%= link_to '新規登録', new_user_path, class: 'nav-link' %>
        </li>

        <li class='nav-item'>
          <%= link_to 'ログイン', login_path, class: 'nav-link' %>
        </li>

        <li class='nav-item'>
          <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
  </nav>
</header>