config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'static_pages#top'
  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :boards do
    member do
      get :confirm_destroy
    end
    resources :comments, only: %i[show create edit update destroy ], shallow: true do
      member do
        get :confirm
      end
    end
  end
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  post 'update_like_count', to: 'likes#update_like_count'
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "title", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["comments", "user"]
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :update, :show, :destroy, :confirm_destroy]
  before_action :check_board_destroy, only: [:confirm_destroy, :destroy]
  before_action :check_board_edit, only: [:edit, :update]

  def index
    @search = Board.ransack(params[:q])
    @boards = @search.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:info] = '掲示板が作成されました'
      redirect_to boards_path
    else
      flash.now[:danger] = '掲示板の作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id]) #bordsテーブルのidを取得している
    @comment = Comment.new #コメントの新規作成
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  def edit
  end

  def update
    if @board.update(board_params)
      flash[:info] = '掲示板が更新されました'
      redirect_to @board
    else
      render :edit
    end
  end

  def confirm_destroy
    # @boardはset_boardで設定済み
  end

  def destroy
    @board.destroy!
    flash[:success] = '掲示板を削除しました'
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:title, :body)
  end

  def set_board
    @board = Board.find(params[:id])
  end

  def check_board_destroy
    unless @board.user_id == current_user.id
      flash[:danger] = '作成した掲示板ではないので、削除できません'
      redirect_to boards_path
    end
  end

  def check_board_edit
    unless @board.user_id == current_user.id
      flash[:danger] = '作成した掲示板ではないので、編集できません'
      redirect_to boards_path
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%= board.id %>">
    <div class="list-group">
      <div class="list-group-item">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= link_to board.title, board_path(board) %></h5>
          <div>
            <%= link_to edit_board_path(board), id: "button-edit-#{board.id}", class: 'btn btn-outline-secondary btn-sm' do %>
              <i class="bi bi-pencil-fill"></i>
            <% end %>
            <%= link_to confirm_destroy_board_path(board), id: "button-delete-#{board.id}", method: :get, data: { confirm: '削除しますか？' }, class: 'btn btn-outline-danger btn-sm' do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </div>
        </div>
        <small><i class="bi bi-person"></i> <%= board.user.decorate.full_name %></small>
        <small><i class="bi bi-calendar"></i> <%= board.created_at.strftime("%Y年%m月%d日 %H:%M") %></small>
        <p class="mb-1 mt-2" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
          <%= board.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/boards/_search_form.html.erb
<%= search_form_for @search, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :title_or_body_cont, class: 'form-control', placeholder: '検索ワード'  %>
    <div class="input-group-append">
      <%= f.submit "検索", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/boards/confirm_destroy.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="card">
        <div class="card-header text-center">
          <h3 class="card-title">掲示板削除確認</h3>
          <p>本当にこの掲示板を削除しますか？</p>
          </div>
          <div class="card-body">

          <%= form_with url: board_path(@board), method: :delete do %>
            <div class="d-flex justify-content-between">
            <%= submit_tag '削除', class: 'btn btn-danger' %>
            <%= link_to 'キャンセル', board_path(@board), class: 'btn btn-secondary' %>
            </div>
          <% end %>
        </div>
        <div class="card-footer text-center">
        <p>質問が解決しても消さないことで他の人のためになるので消さないでくれるとありがたいです。</p>
      </div>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>掲示板を編集</h1>
      <%= form_with model: @board, class: "edit_board" do |f| %>
        <div class="mb-3">
          <%= f.label :title, "タイトル", for: "board_title" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :body, "本文", for: "board_body" %>
          <%= f.text_area :body, class: "form-control", rows: "10" %>
        </div>
        <div class="d-flex justify-content-between">
          <%= f.submit "更新", class: "btn btn-primary" %>
          <%= link_to 'キャンセル', board_path(@board), class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <%= render 'search_form', q: @search, url: boards_path %>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <div class="mb-3">掲示板がありません</div>
        <% end %>
      </div>
      <%= paginate @boards, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>タイトル</h1>
      <%= form_with model: @board, class: "new_board" do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="mb-3">
          <%= f.label :title,"タイトル", for: "board_title" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :body,"本文", for: "board_body" %>
          <%= f.text_area :body, class: "form-control", rows: "10" %>
        </div>
        <%= f.submit "送信", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <article class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-9">
              <h3 style="display: inline;"><%= @board.title %></h3>
              <ul class="list-inline">
                <li class="list-inline-item"><%= "by #{@board.user.decorate.full_name}" %></li>
                <li class="list-inline-item"><%= @board.created_at.strftime("%Y年%m月%d日 %H:%M") %></li>
              </ul>
              <div class='d-flex justify-content-end'>
                <%= link_to edit_board_path(@board), id: "button-edit-#{@board.id}", class: 'btn btn-outline-secondary btn-sm' do %>
                  <i class='bi bi-pencil-fill'></i>
                <% end %>
                <%= link_to confirm_destroy_board_path(@board), id: "button-delete-#{@board.id}",method: :get, data: { confirm: '削除しますか？' }, class: 'btn btn-outline-danger btn-sm' do %>
                  <i class="bi bi-trash-fill"></i>
                <% end %>
              </div>
              </div>
            </div>
            <p><%= simple_format(@board.body) %></p>
          </div>
        </article>
      </div>
    </div>
    <%= render 'comments/form', comment: @comment, board: @board %>
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <table class="table">
          <tbody id="table-comment">
            <%= render @comments %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>