config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'static_pages#top'
  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :boards do
    member do
      get :confirm_destroy
    end
    resources :comments, only: %i[show create edit update destroy ], shallow: true do
      member do
        get :confirm
      end
    end
  end
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  post 'update_like_count', to: 'likes#update_like_count'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      flash[:info] = 'ログインしました'
      redirect_to boards_path
    else
      flash.now[:danger] = 'ログイン失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:info] = 'ログアウトしました'
    redirect_to root_path, status: :see_other
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-10 col-lg-8">
      <div class="card">
        <div class="card-header text-center">
          <h3 class="card-title">MyAppへようこそ</h3>
          <p>アカウントにログインしてください</p>
        </div>
        <div class="card-body">
          <%= form_with url: login_path, local: true do |f| %>
            <div class="mb-3">
              <%= f.label :email, "メールアドレス", class: "form-label" %>
              <%= f.email_field :email, class: "form-control", placeholder: "○○○○@○○○○.com", required: true, autocomplete: "email" %>
            </div>
            <div class="mb-3">
              <%= f.label :password, "パスワード", class: "form-label" %>
              <%= f.password_field :password, class: "form-control", placeholder: "パスワード", required: true, autocomplete: "current-password" %>
            </div>
            <div class="d-grid gap-2">
              <%= f.submit "ログイン", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
        <div class="card-footer text-center">
          <p>アカウントをお持ちではない方 <%= link_to '新規登録へ', new_user_path %></p>
          <p>パスワードをお忘れの方はこちら <%= link_to 'パスワードリセット', new_password_reset_path %></p>
        </div>
      </div>
    </div>
  </div>
</div>